### ISSUE TITLE
Data importing before the launch

### ISSUE THREAD

**Issue by MoeNick** [GeneralMagicio/pairwise-RPGF4#59]
- [ ] Snapshots of weights for OP holders, badge holders, recipients and delegates
- [ ] Projects data and their categorization
- [ ] Project's metrics data
